ccd-orchestrator:
  applicationPort: 8080
  image: hmcts.azurecr.io/hmcts/em-ccd-orchestrator:latest
  readinessDelay: 40
  readinessTimeout: 5
  readinessPeriod: 15
  readinessFailureThreshold: 10
  livenessDelay: 40
  livenessTimeout: 5
  livenessPeriod: 15
  livenessFailureThreshold: 10
  aadIdentityName: em
  keyVaults:
    em-ccd-orchestrator:
      resourceGroup: em-ccd-orchestrator
      secrets:
        - AppInsightsInstrumentationKey
        - microservicekey-em-ccd-orchestrator
  environment:
    # Regardless of environment, point towards AAT instances. Overwrite in product charts etc.
    IDAM_API_BASE_URI: https://idam-api.aat.platform.hmcts.net
    S2S_BASE_URI: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    EM_STITCHING_API_URL: http://em-stitching-aat.service.core-compute-aat.internal
    DM_STORE_APP_URL: http://dm-store-aat.service.core-compute-aat.internal
    CCD_DATA_API_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal

    REFORM_SERVICE_NAME: em-ccd-orchestrator
    REFORM_TEAM: evidence
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    PACKAGES_NAME: em-ccd-orchestrator
    PACKAGES_PROJECT: evidence
    PACKAGES_ENVIRONMENT: preview
    JSON_CONSOLE_PRETTY_PRINT: false
    LOG_OUTPUT: single
    ROOT_LOGGING_LEVEL: INFO
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_DM: INFO
    SHOW_SQL: true
    ENDPOINTS_HEALTH_SENSITIVE: false
    ENDPOINTS_INFO_SENSITIVE: false
    ENABLE_IDAM_HEALTH_CHECK: false
    ENABLE_S2S_HEALTH_CHECK: false
    SERVER_PORT: 8080
    CALLBACK_HTTP_SCHEME: http
    CALLBACK_HTTP_HOST_PORT: 80
